### PR TITLE
Focus root node if focusable

### PR DESCRIPTION
**Pull request by einarlove**
It might not be prettified or TSLinted correctly, but it looks correct.

### CODE REVIEW

**Comment by thebuilder** [comment]
Hey - Can you explain in a bit more detail what this solves? 🤔

**Comment by einarlove** [comment]
Now, useFocusTrap will traverse and find the first tabable child and focus it. Fine if thats what you want, but In my case, I want to trap the focus only. Therefore I make the container focusable—not tabable—and focus that instead.

Take an example: You want a dropdown visible if you click a button. On button click the focus should be on the dropdown as a whole, not the first element using tabIndex="-1" aria-role="list-box" aria-label="Menu" etc. But if the user tabs, the first element is read/focused and so on.

**Comment by thebuilder** [comment]
Makes sense - Do you think you can make an example of it in the storybook? 
So if there isn't specified a `focusSelector` in options, but the root can take focus (with `tabIndex`), then focus is assigned to that instead?

**Comment by einarlove** [comment]
> Makes sense - Do you think you can make an example of it in the storybook?
> So if there isn't specified a `focusSelector` in options, but the root can take focus (with `tabIndex`), then focus is assigned to that instead?

Correct! As long as root is focusable by being `HTMLAnchorElement`, tabIndex etc.

**Comment by einarlove** [comment]
I've added a story

**Comment by thebuilder** [comment]
I'll make a release with this tomorrow. Thanks for adding it!

**Pull request merged**
